apiVersion: v1
kind: ConfigMap
metadata:
  name: ic-webapp-cm
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
data:
  ODOO_URL:    http://15.237.110.114:30010
  PGADMIN_URL: http://15.237.110.114:30011
