apiVersion: v1
kind: ConfigMap
metadata:
  name: ic-webapp-cm
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
data:
  ODOO_URL:    http://35.181.51.111:30010
  PGADMIN_URL: http://35.181.51.111:30011
